//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public Nullable<int> HajjYear { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public Nullable<int> UmrahID { get; set; }
        public string PaymentFor { get; set; }
        public Nullable<int> GroupLeaderID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> HajjiID { get; set; }
    
        public virtual GroupLeader GroupLeader { get; set; }
        public virtual Hajji Hajji { get; set; }
        public virtual Umrah Umrah { get; set; }
    }
}
