//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DagorHajjEntities : DbContext
    {
        public DagorHajjEntities()
            : base("name=DagorHajjEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminSystemUser> AdminSystemUsers { get; set; }
        public virtual DbSet<AdminSystemUserDetail> AdminSystemUserDetails { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<GroupLeader> GroupLeaders { get; set; }
        public virtual DbSet<HajjiStatu> HajjiStatus { get; set; }
        public virtual DbSet<MuharramRelation> MuharramRelations { get; set; }
        public virtual DbSet<Other> Other { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketSector> TicketSectors { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<UmrahStatu> UmrahStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Hajji> Hajjis { get; set; }
        public virtual DbSet<SupplierPayment> SupplierPayments { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Umrah> Umrahs { get; set; }
    }
}
