//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string PackageName { get; set; }
        public decimal PackageRate { get; set; }
        public decimal HajjLevy { get; set; }
        public int LevyYear { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> EditedAt { get; set; }
        public Nullable<int> EditedBy { get; set; }
    }
}
