//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string PaymentFor { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusChangableDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
