//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSector
    {
        public int ID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string Sector { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
