//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umrah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Umrah()
        {
            this.Bookings = new HashSet<Booking>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int ID { get; set; }
        public string UmrahID { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string ContactNo { get; set; }
        public string SpouseContactNo { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public string PlaceOfPassportIssue { get; set; }
        public string NID { get; set; }
        public string PassportAttach { get; set; }
        public string NIDAttach { get; set; }
        public string ImageAttach { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public int CompanyID { get; set; }
        public string MuharramName { get; set; }
        public string InitialName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GroupLeaderID { get; set; }
        public Nullable<int> LastUmrahYear { get; set; }
        public Nullable<int> ContractAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public string District { get; set; }
        public string Thana { get; set; }
        public string PostOffice { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> FlightArrivalDate { get; set; }
        public Nullable<int> MuharramRelationID { get; set; }
        public string PermanentDistrict { get; set; }
        public string PermanentThana { get; set; }
        public string PermanentPostOffice { get; set; }
        public string PermanentPostCode { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> PurchaseAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual GroupLeader GroupLeader { get; set; }
        public virtual MuharramRelation MuharramRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual UmrahStatu UmrahStatu { get; set; }
    }
}
