//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagorHajj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public short RoleId { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLoggedInDateTime { get; set; }
        public short AllowedNoOfLogins { get; set; }
        public short LoginCount { get; set; }
        public short AllowedLoginHours { get; set; }
        public short AllowedLoginMinutes { get; set; }
        public int ActiveBranchId { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
